# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-293-governance-expansion
task: Add governance mappings for 10 remaining significant files
claimed_at: '2026-02-04T14:53:54Z'
session_id: fde5e44d-074d-41de-a04f-d05e83b4eed0
plan: 293
