# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: fix-mint-query-attr
task: Fix kernel_queries referencing wrong MintAuction attribute
claimed_at: '2026-02-02T18:26:35Z'
session_id: eaff7ca3-36bd-4d51-8ab7-4ecc7947fdd3
plan: 260
