# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-285-doc-graph-tooling
task: Add doc graph hook and visualization
claimed_at: '2026-02-04T11:07:59Z'
session_id: ac48b0c2-cc8d-4421-a4e4-44080dde0d91
plan: 285
