# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-232-fix-cwd
task: Fix CWD invalidation after worktree deletion
claimed_at: '2026-01-31T20:12:29Z'
session_id: 42f27964-676a-4a9f-9af3-5783c17f5eef
plan: 232
