# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-295-phase1-ledger-cleanup
task: 'Phase 1: Clean up ledger deprecated code'
claimed_at: '2026-02-05T15:54:52Z'
session_id: d86f74c9-ac1f-4e5c-a281-f6553a48a8ae
plan: 295
