# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-304-stale-refs
task: Fix stale doc references (TD-013)
claimed_at: '2026-02-05T23:55:22Z'
session_id: 3c6ba88f-40c3-4bf3-bd70-b30a20ee2de4
plan: 304
