# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-231-standing-invariant
task: Enforce has_standing <-> ledger invariant
claimed_at: '2026-02-01T00:15:38Z'
session_id: 2f67eed1-4c7e-4928-9fdb-5f2e27ac51ab
plan: 231
