# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-305-tech-debt-cleanup
task: Fix TD-006/007/008/011/012 - remaining low-effort tech debt
claimed_at: '2026-02-06T01:38:36Z'
session_id: be03c62e-c619-4660-b509-1516fe8cdfa0
plan: 305
