# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-297-plan-type-distinction
task: Add plan type distinction to meta-process
claimed_at: '2026-02-05T15:48:55Z'
session_id: 94d0c8fb-a15c-49c0-bf8d-2ccfc46d6355
plan: 297
