# Atomic claim file - this worktree is claimed
# Deleting worktree = releasing claim

cc_id: plan-302-tech-debt-quick-wins
task: Fix TD-011 through TD-014
claimed_at: '2026-02-05T22:44:16Z'
session_id: 463f3b3e-cae8-4e90-84ba-ecf4007aa212
plan: 302
